name: Sync main → develop

on:
  pull_request:
    types: [closed]
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch develop
        run: |
          git fetch origin develop || true

      - name: Checkout develop
        run: |
          if git branch -r | grep origin/develop; then
            git checkout develop
            git reset --hard origin/develop
          else
            git checkout -b develop origin/main
          fi

      - name: Merge main into develop
        id: merge
        run: |
          set -eo pipefail
          git merge origin/main --no-edit || true
          if [ -f .git/MERGE_HEAD ]; then
            echo "conflict=true" >> $GITHUB_OUTPUT
          else
            echo "conflict=false" >> $GITHUB_OUTPUT
          fi

      - name: Abort on conflict
        if: steps.merge.outputs.conflict == 'true'
        run: |
          echo "Merge conflict detected — aborting."
          git merge --abort || true
          exit 1

      - name: Push develop
        if: steps.merge.outputs.conflict == 'false'
        run: |
          git push origin develop

      - name: Notify maintainers on conflict
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const actor = context.actor;
            await github.rest.issues.create({
              owner,
              repo,
              title: "⚠️ Merge conflict: main → develop",
              body: `Hi @${actor},

The automatic merge from **main** into **develop** failed because of conflicts.
Please resolve locally:

\`\`\`bash
git fetch origin
git checkout develop
git merge origin/main
# resolve conflicts
git push origin develop
\`\`\`
`
            });
